Publish ECS docs for beta.5 (#11267)
docker/docker.github.io pull request #11293
Opened 2020-08-25 15:48 UTC by usha-mandya

Publish the latest docs for ECS beta 5 release

2020-08-25 17:12 UTC, StefanScherer requested changes

2020-08-25 17:12 UTC, StefanScherer commented on engine/context/ecs-integration.md
> +Compose file with the `docker  compose up` command. The following sections
There are two spaces, one should be removed.

2020-08-25 17:12 UTC, StefanScherer commented on engine/context/ecs-integration.md
> +Compose file with the `docker  compose up` command. The following sections
There are two spaces, one should be removed.

2020-08-25 17:58 UTC, usha-mandya commented
@StefanScherer PTAL - https://github.com/docker/docker.github.io/pull/11295

2020-08-26 05:24 UTC, StefanScherer approved these changes
LGTM

2020-08-26 12:36 UTC, StefanScherer approved these changes
LGTM

2020-08-26 12:36 UTC, merged