Add indication to use docker create/run on port mapping #11420
docker/docker.github.io pull request #11429
Opened 2020-09-26 19:05 UTC by maximillianfx

Signed-off-by: Maximillian Fan Xavier <maximillianfx@gmail.com>

Proposed changes
Add some extra info to documentation to indicate the use of docker run/create when executing port mapping.

Related issues (optional)
#11420

2020-09-28 11:44 UTC, usha-mandya commented
Thank you for the update @maximillianfx.

@thaJeztah Could you PTAL?

2020-09-28 12:30 UTC, thaJeztah requested changes
thanks! I left a suggestion, but otherwise looks good

2020-09-28 12:30 UTC, thaJeztah commented on config/containers/container-networking.md
> +By default, when you create/run a container using `docker create` or `docker run`, it does not publish any of its ports
Perhaps change the `create/run` to "create or run". Also looks like this line is now quite a bit longer than 80 chars (which is what we try to use as width), so may need some wrapping;

```suggestion
By default, when you create or run a container using `docker create` or `docker run`,
it does not publish any of its ports to the outside world. To make a port available
to services outside of Docker, or to Docker containers which are not connected to
the container's network, use the `--publish` or `-p` flag. This creates a firewall
rule which maps a container port to a port on the Docker host. Here are some examples.
```

2020-09-28 13:11 UTC, usha-mandya approved these changes

2020-09-28 13:12 UTC, usha-mandya commented
@thaJeztah Looks like you need to approve the PR.

2020-09-29 16:23 UTC, thaJeztah approved these changes
LGTM, thanks!

2020-09-29 16:24 UTC, merged