Docker Desktop 3.0.3 release notes
docker/docker.github.io pull request #11956
Opened 2020-12-21 14:49 UTC by ebriney

### Proposed changes

### Unreleased project version (optional)

### Related issues (optional)

2020-12-28 20:35 UTC, qhenkart commented
3.0.3 broke https://github.com/docker/for-mac/issues/5124 which was fixed in 3.0.2.  The steps in the issue can be easily replicated to show the fsnotify event DELETE firing in every container when another container is mounted

2021-01-05 12:13 UTC, thaJeztah commented
@stephen-turner @StefanScherer PTAL

Should we add https://github.com/docker/docker.github.io/pull/11956#issuecomment-751856085 to the "known issues" in this PR?

2021-01-05 17:46 UTC, stephen-turner requested changes

2021-01-05 17:46 UTC, stephen-turner commented on docker-for-mac/release-notes.md
> +- Rollback gprcfuse patches that fixed [docker/for-mac#4957](https://github.com/docker/for-mac/issues/4957) and [docker/for-mac#5124](https://github.com/docker/for-mac/issues/5124). They broke widely
I think the sentence needs to be in the opposite order:

- Fixed an issue that caused overlapping volume mounts to fail. Fixes [docker/for-mac#5157](https://github.com/docker/for-mac/issues/5157). However, the fixes for [docker/for-mac#4957](https://github.com/docker/for-mac/issues/4957) and [docker/for-mac#5124](https://github.com/docker/for-mac/issues/5124) have been reverted as a result of this change, so those issues are now present again.

2021-01-05 17:46 UTC, stephen-turner commented on docker-for-mac/release-notes.md
> +
Add:

- There can be timeouts during `docker-compose up` if there are several services being started. See [docker/for-mac#4957](https://github.com/docker/for-mac/issues/4957) and [docker/for-mac#5124](https://github.com/docker/for-mac/issues/5124).

2021-01-06 12:43 UTC, thaJeztah commented
@ebriney can you address @stephen-turner's comments?

2021-01-06 13:32 UTC, stephen-turner approved these changes
Thanks, looks good now.

2021-01-06 13:32 UTC, merged