fix: docker build with URL example
docker/docker.github.io pull request #12119
Opened 2021-01-18 09:16 UTC by scraly

Hi,

### Proposed changes

The original example in order to build from an URL didn't works so I debug in my side and found a command that works

KO:

`$ docker build github.com/creack/docker-firefox
`
WORKS:

`$ docker build https://github.com/creack/docker-firefox.git
`

2021-01-18 09:19 UTC, thaJeztah requested changes
what version of Docker are you running? Both variants should work (that is; building should work, although it looks like the example repository that it builds from may need an update)

2021-01-18 09:24 UTC, scraly commented
Hi,

here my docker version:

`$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`

2021-01-18 09:29 UTC, thaJeztah commented
Trying to reproduce on a current version of Docker Desktop, but don't see it failing;

```console
$ docker build github.com/creack/docker-firefox
[+] Building 3.3s (6/9)
 => CACHED [internal] load git source github.com/creack/docker-firefox                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/ubuntu:12.04                                                                                                                                        2.5s
 => [1/7] FROM docker.io/library/ubuntu:12.04@sha256:18305429afa14ea462f810146ba44d4363ae76e4c8dfc38288cf73aa07485005                                                                                  0.0s
 => CACHED [2/7] RUN ECHO "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list                                                                                         0.0s
 => CACHED [3/7] RUN APT-GET update
...
```

Looks like you are on a slightly older patch release of Docker though. My reproduction steps are done on this version;

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

2021-01-18 09:34 UTC, scraly commented
Here my logs:

```
$ docker build github.com/creack/docker-firefox.git
[+] Building 0.0s (1/1) FINISHED
 => ERROR [internal] load git source github.com/creack/docker-firefox.git                                                                                                                                                                                0.0s
------
 > [internal] load git source github.com/creack/docker-firefox.git:
#1 0.013 Initialized empty Git repository in /var/lib/docker/overlay2/zassjrc6i5maassvp50dxry9n/diff/
#1 0.019 fatal: 'github.com/creack/docker-firefox.git' does not appear to be a git repository
#1 0.019 fatal: Could not read from remote repository.
#1 0.019
#1 0.019 Please make sure you have the correct access rights
#1 0.019 and the repository exists.
------
failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: failed to fetch remote github.com/creack/docker-firefox.git: exit status 128
```

```
$ docker build https://github.com/creack/docker-firefox.git
[+] Building 13.2s (7/10)
 => [internal] load git source https://github.com/creack/docker-firefox.git                                                                                                                                                                              1.1s
 => [internal] load metadata for docker.io/library/ubuntu:12.04                                                                                                                                                                                          1.8s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                                                                            0.0s
 => [1/7] FROM docker.io/library/ubuntu:12.04@sha256:18305429afa14ea462f810146ba44d4363ae76e4c8dfc38288cf73aa07485005                                                                                                                                    5.1s
 => => resolve docker.io/library/ubuntu:12.04@sha256:18305429afa14ea462f810146ba44d4363ae76e4c8dfc38288cf73aa07485005                                                                                                                                    0.0s
 => => sha256:18305429afa14ea462f810146ba44d4363ae76e4c8dfc38288cf73aa07485005 1.36kB / 1.36kB                                                                                                                                                           0.0s
 => => sha256:5b117edd0b767986092e9f721ba2364951b0a271f53f1f41aff9dd1861c2d4fe 3.62kB / 3.62kB                                                                                                                                                           0.0s
 => => sha256:d8868e50ac4c7104d2200d42f432b661b2da8c1e417ccfae217e6a1e04bb9295 39.10MB / 39.10MB                                                                                                                                                         2.7s
 => => sha256:83251ac64627fc331584f6c498b3aba5badc01574e2c70b2499af3af16630eed 57.94kB / 57.94kB                                                                                                                                                         0.4s
 => => sha256:589bba2f1b36ae56f0152c246e2541c5aa604b058febfcf2be32e9a304fec610 423B / 423B                                                                                                                                                               0.4s
 => => sha256:d62ecaceda3964b735cdd2af613d6bb136a52c1da0838b2ff4b4dab4212bcb1c 680B / 680B                                                                                                                                                               0.7s
 => => sha256:6d93b41cfc6bf0d2522b7cf61588de4cd045065b36c52bd3aec2ba0622b2b22b 162B / 162B                                                                                                                                                               0.6s
 => => extracting sha256:d8868e50ac4c7104d2200d42f432b661b2da8c1e417ccfae217e6a1e04bb9295                                                                                                                                                                1.7s
 => => extracting sha256:83251ac64627fc331584f6c498b3aba5badc01574e2c70b2499af3af16630eed                                                                                                                                                                0.0s
 => => extracting sha256:589bba2f1b36ae56f0152c246e2541c5aa604b058febfcf2be32e9a304fec610                                                                                                                                                                0.0s
 => => extracting sha256:d62ecaceda3964b735cdd2af613d6bb136a52c1da0838b2ff4b4dab4212bcb1c                                                                                                                                                                0.0s
 => => extracting sha256:6d93b41cfc6bf0d2522b7cf61588de4cd045065b36c52bd3aec2ba0622b2b22b                                                                                                                                                                0.0s
 => [2/7] RUN ECHO "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list                                                                                                                                                  0.5s
 => [3/7] RUN APT-GET update                                                                                                                                                                                                                             ...
```

2021-01-18 10:51 UTC, thaJeztah commented
I think that was a bug in Docker v20.10.0, which was fixed in Docker v20.10.1 and up through https://github.com/moby/buildkit/pull/1886 / https://github.com/moby/moby/pull/41793

Do you still  see that problem when updating to the latest version of Docker Desktop?

2021-01-18 10:58 UTC, scraly commented
Since I've upgraded in 20.10.2, the bug is fixed.

```
$ docker build github.com/creack/docker-firefox
[+] Building 4.8s (7/10)
 => CACHED [internal] load git source github.com/creack/docker-firefox                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:12.04                                                                                                                                                                                          1.9s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                                                                            0.0s
 => [1/7] FROM docker.io/library/ubuntu:12.04@sha256:18305429afa14ea462f810146ba44d4363ae76e4c8dfc38288cf73aa07485005                                                                                                                                    0.0s
 => CACHED [2/7] RUN ECHO "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list                                                                                                                                           0.0s
 => CACHED [3/7] RUN APT-GET update                                                                                                                                                                                                                      0.0s
 => ERROR [4/7] RUN APT-GET install -y x11vnc xvfb firefox
```

2021-01-19 14:17 UTC, usha-mandya commented
Thank you @scraly. Closing this PR as the updates are not required anymore. Thanks again for your PR.

2021-01-19 14:17 UTC, closed without merging