aws elbv2 correction & x-aws-pull_policy mentioned
docker/docker.github.io pull request #12117
Opened 2021-01-17 20:54 UTC by umutykaya

-  Subnet ids should be passed withou quotation mark (""). 
- x-aws-pull_policy mentioned in documentation with a tested example.

### Proposed changes

### Unreleased project version (optional)

### Related issues (optional)

2021-01-18 14:57 UTC, usha-mandya commented
@ndeloof Could you PTAL?

2021-01-18 20:22 UTC, ndeloof commented on cloud/ecs-integration.md
> +Once created, you can use this ARN in you Compose file using using `x-aws-pull_credentials` custom extension with the Docker image URI for your service. For AWS ECR Registry private repository, use `
We configure ECS Task with ECRReadAccess permission so this should **not** be required. Please open an issue on docker/compose-cli if you have to

2021-01-18 20:27 UTC, ndeloof requested changes
reference to x-aws-pull_policy is wrong
(and is not needed: compose spec do define [pull_policy](https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy attribute)

requirement for credentials accessing ECR is not expected

2021-01-18 20:27 UTC, ndeloof commented on cloud/ecs-integration.md
> +Once created, you can use this ARN in you Compose file using using `x-aws-pull_credentials` custom extension with the Docker image URI for your service. For AWS ECR Registry private repository, use `
reference to `x-aws-pull_policy` is a mistake, we don't define such an extension
https://github.com/docker/compose-cli/blob/main/ecs/x.go#L20-L33

2021-01-19 14:20 UTC, usha-mandya commented
Thanks for the PR @umutykaya. Closing this out as per @ndeloof's comment above. Feel free to continue the conversation after I close.

2021-01-19 14:20 UTC, closed without merging