Fix uninstall command for Debian
docker/docker.github.io pull request #12464
Opened 2021-03-09 10:35 UTC by gtklocker

### Proposed changes

apt-get remove with multiple packages will stop on the first package that is not installed

### Unreleased project version (optional)

### Related issues (optional)

2021-03-09 14:51 UTC, thaJeztah requested changes

2021-03-09 14:51 UTC, thaJeztah commented on engine/install/debian.md
> +$ for pkg in docker docker-engine docker.io containerd runc; do sudo apt-get remove -y $pkg; done
I'm a bit concerned that the command becomes longer (and potentially more error-prone for users to follow); wondering if instead we should use `dpkg --remove` (as suggested in https://superuser.com/a/518871)

```suggestion
$ sudo dpkg --remove docker docker-engine docker.io containerd runc
```

2021-03-09 14:51 UTC, thaJeztah commented on engine/install/debian.md
> +$ for pkg in docker docker-engine docker.io containerd runc; do sudo apt-get remove -y $pkg; done
If we update, we should also update the ubuntu page with the same changes

2022-04-22 10:18 UTC, usha-mandya commented
Closing this PR as there isn't any activity on the PR.

2022-04-22 10:18 UTC, closed without merging