Add image management docs
docker/docker.github.io pull request #12502
Opened 2021-03-15 14:29 UTC by usha-mandya

Signed-off-by: Usha Mandya <usha.mandya@docker.com>

Add docs for Advanced image management dashboard

2021-03-15 14:53 UTC, usha-mandya commented
Preview - https://deploy-preview-12502--docsdocker.netlify.app/docker-hub/image-management/

2021-03-17 10:02 UTC, mark-dr reviewed
Is it okay to use internal test users for screenshots in the docs?

- scan-e2e isn't just a test repo, it's really used for some of our e2e tests
- `testuserproplan` has a pretty silly (and maybe copyrighted :grimacing:) avatar

It feels a bit like we're showing the users how the sausages are made.

2021-03-17 10:53 UTC, usha-mandya commented
Thanks for the review @mark-dr. Didn't want to use the dummy data, so added this screenshot instead. Is there an example repo I can log into to get a screenshot?

2021-03-17 12:41 UTC, mark-dr commented
LGTM, thanks for the changes :slightly_smiling_face:

2021-03-17 15:08 UTC, usha-mandya commented
Removed the 'Image Management API' section.

2021-03-18 09:58 UTC, nebuk89 requested changes
Added a section to provide more explanation on what users will be seeing

2021-03-18 09:58 UTC, nebuk89 commented on docker-hub/image-management.md
> +By displaying the activity status and tags, the dashboard makes it easier for you to review the existing images and take actions to delete images that are not needed anymore. This is particularly hel
add in:

You can also see the old versions of images you have pushed. When you push an image to Docker Hub you are pushing a manifest, a list of all of the layers of your image, and the layers themselves. When you are updating an existing tag, only the new layers will be pushed along with the new manifest which references these layers. This new manifest will be given the tag you specify when you push, such as myNamespace/mytag:latest. This does not remove the old manifests or the unique layers referenced by them from Hub.
You can in still use and reference these using the digest of the manifest if you know the SHA.

With the new Advanced Image management Dashboard all of this is now accessible for you to browse, use and clean up.

2021-03-22 18:19 UTC, FranchommeE approved these changes
LGTM

- wording around plan/subscription can be updated later (voice and tone)
- link to Hub API doc will 404 until https://docker.atlassian.net/browse/HUB-4980 PR is merged

2021-03-22 18:30 UTC, merged