Add release notes for 20.10.6
docker/docker.github.io pull request #12604
Opened 2021-04-01 10:59 UTC by tiborvass

Signed-off-by: Tibor Vass <tibor@docker.com>

2021-04-01 12:03 UTC, tiborvass commented on engine/release-notes/index.md
> +* overlay2: fix "createDirWithOverlayOpaque(...) ... input/output error" [moby/moby#42188](https://github.com/moby/moby/pull/42188)
oops, this is not the cherrypick

2021-04-01 13:23 UTC, tiborvass commented on engine/release-notes/index.md
> +* overlay2: fix "createDirWithOverlayOpaque(...) ... input/output error" [moby/moby#42188](https://github.com/moby/moby/pull/42188)
should be https://github.com/moby/moby/pull/42235

2021-04-12 10:43 UTC, StefanScherer requested changes
Only a nit, but the release date should be updated.

2021-04-12 10:43 UTC, StefanScherer commented on engine/release-notes/index.md
> +2021-04-01
The date should be updated.

2021-04-12 13:31 UTC, chris-crone reviewed
One addition then LGTM

2021-04-12 13:31 UTC, chris-crone commented on engine/release-notes/index.md
> +
```suggestion
* Add the [Docker Scan CLI](https://github.com/docker/scan-cli-plugin) plugin

```

2021-04-12 13:51 UTC, thaJeztah commented on engine/release-notes/index.md
> +
We should mention it's currently x86 only

I earlier wrote;

- Provide docker scan CLI plugin through the `docker-scan-plugin` package on Linux (x86)
- Add docker scan plugin as "recommended" dependency for the `docker-ce-cli`  package on Linux (x86)

But perhaps that's too technical; wdyt, @chris-crone ?

2021-04-12 13:52 UTC, chris-crone commented on engine/release-notes/index.md
> +
Yes, it'd be good to say x86 only as that impacts users

2021-04-12 17:08 UTC, tiborvass commented on engine/release-notes/index.md
> +
```
* Provide the [Docker Scan CLI](https://github.com/docker/scan-cli-plugin) plugin on Linux amd64 via a `docker-scan-plugin` package as a recommended dependency for the `docker-ce-cli` package [docker/docker-ce-packaging#537](https://github.com/docker/docker-ce-packaging/pull/537)
```

2021-04-12 17:15 UTC, tiborvass commented
@chris-crone @thaJeztah updated with reference to docker scan plugin and new distros. PTAL

2021-04-12 17:27 UTC, thaJeztah approved these changes
LGTM

2021-04-12 17:46 UTC, chris-crone approved these changes
LGTM

2021-04-12 17:56 UTC, merged