Add docs for billing info updates
docker/docker.github.io pull request #12664
Opened 2021-04-12 22:38 UTC by usha-mandya

Signed-off-by: Usha Mandya <usha.mandya@docker.com>

Release note on how to add a new email address to receive billing-related information for an org.

2021-04-13 16:00 UTC, FranchommeE approved these changes
Left a few comments with suggestions. I could be easily convinced I am wrong on those :-) , I think these are not blockers anyway.
So giving 👍

2021-04-13 16:26 UTC, Muhammadariesta approved these changes

2021-04-13 18:38 UTC, FranchommeE requested changes
Found 1 typo.
Other than that, 👍

2021-04-13 18:38 UTC, FranchommeE commented on docker-hub/release-notes.md
> +# 20201-04-13
```suggestion
# 2021-04-13
```
Typo - remove extra 0 in the Year

2021-04-14 13:26 UTC, FranchommeE approved these changes
LGTM

2021-04-14 13:27 UTC, merged