removed legacy info
docker/docker.github.io pull request #12839
Opened 2021-05-12 16:02 UTC by jerae-duffin

Deleted Legacy information in Docker Hub/Billing

2021-05-13 13:29 UTC, FranchommeE requested changes
@jerae-duffin @usha-mandya I made a comment about the link to Pricing FAQ, and (attempted to) commit another change in the Overview (note mentioning Legacy plans in the past tense)

2021-05-13 13:29 UTC, FranchommeE commented on docker-hub/billing/upgrade.md
> +If you were previously on a legacy per-repository plan, your plan has been converted to a new Pro or Team monthly plan. For details, see [Resource Consumption FAQs](https://www.docker.com/pricing/res
```suggestion
If you were previously on a legacy per-repository plan, your plan has been converted to a new Pro or Team monthly plan. For details, see [Pricing FAQ](faq.md).
```
I think we should link to the Pricing FAQ instead (the Resource consumption faq isn't about the legacy plan conversion). Please check the syntax of the link I suggest, and whether it should open in a new tab.

2021-05-13 14:14 UTC, jerae-duffin commented
@FranchommeE I've added a commit. Can you review and approve.

2021-05-17 06:00 UTC, usha-mandya approved these changes

2021-05-17 10:20 UTC, merged