Update django.md
docker/docker.github.io pull request #12851
Opened 2021-05-16 05:48 UTC by fazchow

Added data folder that is created and the fact that we should not change its permission from root was made more explicit.

### Proposed changes

Added some clarification about the data folder permission that might cause permission issues with docker-compose up if folder ownership is not root

### Unreleased project version (optional)

### Related issues (optional)

2021-07-02 18:34 UTC, crydotsnake requested changes

2021-07-02 18:34 UTC, crydotsnake commented on samples/django.md
> +   $ sudo chown -R $USER:$USER composeexample manage.py
I would use `sudo chown -R $USER:$USER compose-example manage.py` for better reading.

2022-04-22 09:19 UTC, usha-mandya approved these changes
LGTM. Thank you @fazchow

2022-04-22 10:37 UTC, usha-mandya commented
Close and reopen to trigger build checks

2022-04-22 10:41 UTC, merged