DOCS: Added support for arch s390x for Ubuntu, RHEL and SLES
docker/docker.github.io pull request #13231
Opened 2021-07-26 12:34 UTC by nirmannarang

Signed-off-by: Nirman Narang <narang@us.ibm.com>

### Proposed changes
Added .md files for SLES and RHEL engine installation.
Added indexing to _data/toc.yaml and engine/install/index.md.
Modified engine/install/index.md, includes/install-script.md, engine/security/rootless.md, storage/storagedriver/device-mapper-driver.md, and storage/storagedriver/select-storage-driver.md to add info for added RHEL and SLES support.
Modified engine/install/ubuntu.md to add s390x repos and other info.
Added tab target for RHEL and SLES to engine/security/rootless.md along with other info.

2021-07-28 09:43 UTC, thaJeztah requested changes
Thanks! I left some comments/suggestions inline

2021-07-28 09:43 UTC, thaJeztah commented on engine/install/rhel.md
> +keywords: requirements, apt, installation, rhel, rpm, install, uninstall, upgrade, update
Perhaps add `s390x` and `ibm-z` here (I think that makes it pop-up in the auto-complete when searching)

```suggestion
keywords: requirements, apt, installation, rhel, rpm, install, uninstall, upgrade, update, s390x, ibm-z
```

2021-07-28 09:43 UTC, thaJeztah commented on engine/install/sles.md
> +keywords: requirements, apt, installation, centos, rpm, sles, install, uninstall, upgrade, update
Same here

```suggestion
keywords: requirements, apt, installation, centos, rpm, sles, install, uninstall, upgrade, update, s390x, ibm-z
```

2021-07-28 09:43 UTC, thaJeztah commented on engine/install/sles.md
> +
Given that this distro is only available on s390x currently, perhaps it's good to highlight that a bit more, e.g.:

```suggestion
## Prerequisites

> **Note**
>
> We currently only provide packages for SLES on s390x (IBM Z). Other architectures
> are not yet supported for SLES.

```

2021-08-05 12:36 UTC, thaJeztah commented
I pushed https://github.com/docker/docker.github.io/pull/13288 with my suggestions

2021-08-05 12:56 UTC, nirmannarang commented
> I pushed #13288 with my suggestions

Thanks, @thaJeztah. For `SLES 15`, the kernel version available is `5.3.18-24.46`, but rootless could not be started with `overlay2`.

2021-08-05 19:28 UTC, thaJeztah commented
> Thanks, @thaJeztah. For `SLES 15`, the kernel version available is `5.3.18-24.46`, but rootless could not be started with `overlay2`.

Ah, right, so `5.3` < `5.11`, so from that perspective it should already be covered by the "requires kernel 5.11 or up"

2021-08-06 08:25 UTC, closed without merging