WIP: Remove hard requirement to install Rosetta 2 for DD 4.3.0
docker/docker.github.io pull request #13895
Opened 2021-11-26 16:15 UTC by StefanScherer

Signed-off-by: Stefan Scherer <stefan.scherer@docker.com>

### Proposed changes

With Docker Desktop 4.3.0 we remove the hard requirement to have Rosetta 2 installed on Apple silicon machines. The Docker Desktop app, the UI, the VM runs natively on Apple silicon. Only a few optional command line tools are still Intel binaries.

### Unreleased project version (optional)

### Related issues (optional)

2021-11-29 18:12 UTC, stephanierifai requested changes
LGTM ! One nit

2021-11-29 18:12 UTC, stephanierifai commented on desktop/mac/apple-silicon.md
> +Beginning with Docker Desktop 4.3.0 we have removed the hard requirement to have **Rosetta 2** installed. There are a few optional command line tools still Darwin/AMD64, see the known issues section
```suggestion
Beginning with Docker Desktop 4.3.0 we have removed the hard requirement to have **Rosetta 2** installed. There are a few optional command line tools still when using Darwin/AMD64, see the known issues section below. However, to have the best experience we do suggest installing Rosetta 2. To install Rosetta 2 manually from the command line, run the following command:
```

2021-11-29 18:44 UTC, StefanScherer commented on desktop/mac/apple-silicon.md
> +Beginning with Docker Desktop 4.3.0 we have removed the hard requirement to have **Rosetta 2** installed. There are a few optional command line tools still Darwin/AMD64, see the known issues section
Thanks!

2021-11-30 16:42 UTC, usha-mandya commented on desktop/mac/apple-silicon.md
> +Beginning with Docker Desktop 4.3.0 we have removed the hard requirement to have **Rosetta 2** installed. There are a few optional command line tools still when using Darwin/AMD64, see the known issu
```suggestion
Beginning with Docker Desktop 4.3.0, we have removed the hard requirement to install **Rosetta 2**. There are a few optional command line tools that still require Rosetta 2 when using Darwin/AMD64. See the Known issues section below. However, to get the best experience, we recommend that you install Rosetta 2. To install Rosetta 2 manually from the command line, run the following command:
```

2021-11-30 16:42 UTC, usha-mandya commented on desktop/mac/apple-silicon.md
> +- Some command line tools are not working when Rosetta 2 is not installed.
```suggestion
- Some command line tools do not working when Rosetta 2 is not installed.
```

2021-11-30 16:43 UTC, usha-mandya commented on desktop/mac/apple-silicon.md
> +  - The old version 1.x of `docker-compose`. It is recommended to use Compose V2 instead. Either type `docker compose` or enable the `Use Docker Compose V2` in the [General preferences tab](./index.m
```suggestion
  - The old version 1.x of `docker-compose`. We recommend that you use Compose V2 instead. Either type `docker compose` or enable the **Use Docker Compose V2** option in the [General preferences tab](./index.md#general).
```

2021-11-30 16:46 UTC, usha-mandya commented
Thanks @StefanScherer. Noted some minor suggestions. Looks good otherwise. We'll also have to update the system requirements on the Install page - https://docs.docker.com/desktop/mac/install/#system-requirements

2021-11-30 17:10 UTC, StefanScherer commented on desktop/mac/apple-silicon.md
> +Beginning with Docker Desktop 4.3.0 we have removed the hard requirement to have **Rosetta 2** installed. There are a few optional command line tools still when using Darwin/AMD64, see the known issu
Thanks!

2021-11-30 17:10 UTC, StefanScherer commented on desktop/mac/apple-silicon.md
> +- Some command line tools are not working when Rosetta 2 is not installed.
"do not work", yes, I'll update that.

2021-11-30 17:11 UTC, StefanScherer commented on desktop/mac/apple-silicon.md
> +  - The old version 1.x of `docker-compose`. It is recommended to use Compose V2 instead. Either type `docker compose` or enable the `Use Docker Compose V2` in the [General preferences tab](./index.m
Thank you.

2021-11-30 19:48 UTC, stephanierifai approved these changes
LGTM !

2021-12-01 11:57 UTC, usha-mandya approved these changes
LGTM. Thanks @StefanScherer

2021-12-02 14:18 UTC, merged