updated SSO docs
docker/docker.github.io pull request #14279
Opened 2022-02-17 23:10 UTC by jerae-duffin

Updated SSO docs and image

2022-02-18 15:27 UTC, usha-mandya approved these changes

2022-02-18 23:36 UTC, technicallyjosh approved these changes

2022-02-18 23:47 UTC, technicallyjosh requested changes
Just some minor edits now.

2022-02-18 23:47 UTC, technicallyjosh commented on single-sign-on/index.md
> +* **SAML 2.0**: Entity ID, ACS URL, Single Logout URL and X.509 certificate
```suggestion
* **SAML 2.0**: Single Sign-On URL and the X.509 signing certificate
```

2022-02-18 23:47 UTC, technicallyjosh commented on single-sign-on/index.md
>  To enable SSO in Docker Hub, you need the following:
```suggestion
To enable SSO in Docker Hub, you need the following information from your identity provider:
```

2022-02-18 23:47 UTC, technicallyjosh commented on single-sign-on/index.md
> +    > For example, <Subject><NameID>yourname@mycompany.com</NameID>. We also support the optional name attribute key; you must use lower-case text only.
```suggestion
    > For example, <Subject><NameID>yourname@mycompany.com</NameID>. We also support the optional `name` attribute. This attribute name must be lower-cased. _The following is an example of this attribute in Okta._
```

2022-02-22 16:47 UTC, jerae-duffin commented on single-sign-on/index.md
> +    > For example, <Subject><NameID>yourname@mycompany.com</NameID>. We also support the optional name attribute key; you must use lower-case text only.
Thanks Josh!

2022-02-22 18:50 UTC, usha-mandya approved these changes
LGTM

2022-02-22 19:05 UTC, merged