DKP-168 Remove support for Windows versions which are not supported by Microsoft anymore
docker/docker.github.io pull request #14623
Opened 2022-04-27 07:48 UTC by mat007

### Proposed changes

Remove support for obsolete Windows versions, according to https://docs.microsoft.com/en-us/windows/release-health/supported-versions-windows-client#servicing-channels

The actual end of support date for these is May 10, 2022. Do we want to wait until then before merging? @usha-mandya @stephen-turner ?

### Related issues (optional)

https://docker.atlassian.net/browse/DKP-168

2022-04-27 08:49 UTC, usha-mandya commented
@mat007 Thanks for the update. I'd suggest we wait until the actual end of servicing date as it's less than two weeks away from now.

2022-04-27 09:32 UTC, stephen-turner requested changes
The edit is good, but we need to make the parallel change in the Hyper-V section too.

2022-04-27 09:32 UTC, stephen-turner commented
> @mat007 Thanks for the update. I'd suggest we wait until the actual end of servicing date as it's less than two weeks away from now.

+1

2022-04-27 10:31 UTC, mat007 commented
> The edit is good, but we need to make the parallel change in the Hyper-V section too.

Oh good catch! 🤦 
Fixed!

2022-04-27 10:35 UTC, stephen-turner approved these changes
Thanks, approved the edit now, but let's hold until May 11.

2022-05-11 09:02 UTC, ebriney approved these changes
LGTM

2022-05-11 09:09 UTC, merged