updated billing events
docker/docker.github.io pull request #15374
Opened 2022-08-12 15:00 UTC by jerae-duffin

New updates to Billing events

2022-08-12 15:09 UTC, leslielylee requested changes
One change for the "Billing Cycle Changed" description. This happens when the org owner changes their billing cycle (e.g. monthly to annual).

Can we change the description to something like "Occurs when there is a change in the recurring interval that your organization is charged"?

2022-08-12 15:16 UTC, leslielylee approved these changes
LGTM. Please wait for @ob1dev to finish his review prior to merging, thank you!

2022-08-12 21:34 UTC, ob1dev approved these changes
Looks good to me.

**nitpick:** Do we want to add a short overview for each table? 

For example: `Contains all activities related to an organization's billing.` under https://github.com/docker/docker.github.io/blob/master/docker-hub/audit-log.md#billing-events

2022-08-12 21:34 UTC, ob1dev commented on docker-hub/audit-log.md
> +| Plan Downgrade Canceled | Occurs when a scheduled downgrade for your organization is canceled.|
```suggestion
| Plan Downgrade Canceled | Occurs when a scheduled plan downgrade for your organization is canceled.|
```

2022-08-16 14:00 UTC, craig-osterhout approved these changes
LGTM

2022-08-16 14:03 UTC, merged