Engdocs 1941
docker/docker.github.io pull request #19083
Opened 2024-01-11 15:00 UTC by aevesdocker

Part of https://www.notion.so/dockerinc/Compose-spec-deprecation-427b924a1aa0435e959d68ddd8716dbb

This simple PR moves the content into our repo. More to follow. 

cc @glours @ndeloof

2024-01-11 15:36 UTC, dvdksn commented
I don't think the data file for `docker init` is maintained in an upstream repo.

https://github.com/docker/docs/blob/766c54fe380317cefeb33b182112b3cc8a084721/data/init-cli/docker_init.yaml

cc @craig-osterhout

2024-01-11 16:34 UTC, craig-osterhout commented
> I don't think the data file for `docker init` is maintained in an upstream repo.
> 
> https://github.com/docker/docs/blob/766c54fe380317cefeb33b182112b3cc8a084721/data/init-cli/docker_init.yaml
> 
> cc @craig-osterhout

Correct, it's currently not maintained upstream.

2024-01-11 16:43 UTC, dvdksn commented
Could you rebase so that the vendor commit (fd6fb9c77b31013d9afa5e6ba41ec872bad8c40a) is in a separate commit, and the other commits are squashed?

2024-01-11 18:11 UTC, dvdksn commented
A squashed diff will show these files as having been moved from the _vendor dir to the content dir. Also I see that the content is different in these files. Maybe we should instead do this in three commits

- update the compose import first so it's on the latest commit
- then remove the vendoring
- add the files, ideally preserving history?

2024-01-12 12:37 UTC, ndeloof approved these changes

2024-01-12 12:45 UTC, usha-mandya submitted a review, later dismissed
Thanks for moving forward with this update @aevesdocker. Maintaining the upstream compose-spec will involve a wider discussion. Let's go ahead with the docs changes so we are not blocked on this.

2024-01-12 14:06 UTC, glours requested changes
I think we have lost parts of the `services.md` file

2024-01-12 14:06 UTC, glours commented on content/compose/compose-file/05-services.md
> +---
Why do we lost all the attributes from `attach` to `cap_drop` during the move of the file? Also the title for the `cgroup` argument is missing

2024-01-12 14:21 UTC, glours approved these changes
LGTM

2024-01-12 14:22 UTC, usha-mandya submitted a review, later dismissed

2024-01-12 14:22 UTC, usha-mandya commented
:shipit:

2024-01-12 14:37 UTC, usha-mandya approved these changes

2024-01-12 14:39 UTC, merged