ENGDOCS-2181c
docker/docker.github.io pull request #21419
Opened 2024-11-13 12:31 UTC by aevesdocker

## Description

Replaces https://github.com/docker/docs/pull/20646 that was so old it was still using the `toc.yaml` file. 
SME reviews complete. Just need editorial 

## Related issues or tickets

## Reviews

- [ ] Technical review
- [x] Editorial review
- [ ] Product review

2024-11-13 16:11 UTC, sarahsanders-docker commented on content/manuals/security/for-admins/hardened-desktop/settings-management/configure-admin-console.md
> +This page contains information for administrators on how to configure Settings Management with the Docker Admin Console to specify and lock configuration parameters to create a standardized Docker De
```suggestion
This page contains information for administrators on how to configure Settings Management with the Docker Admin Console. You can specify and lock configuration parameters to create a standardized Docker Desktop environment across your company or organization.
```

2024-11-13 16:11 UTC, sarahsanders-docker commented on content/manuals/security/for-admins/hardened-desktop/settings-management/configure-admin-console.md
> +This page contains information for administrators on how to configure Settings Management with the Docker Admin Console to specify and lock configuration parameters to create a standardized Docker De
just a suggestion for readability

2024-11-13 16:16 UTC, sarahsanders-docker commented on content/manuals/security/for-admins/hardened-desktop/settings-management/configure-admin-console.md
> +- Make sure you have [verified your domain](/manuals/security/for-admins/single-sign-on/configure.md#step-one-add-and-verify-your-domain)
just a suggestion for simplicity

2024-11-13 16:17 UTC, sarahsanders-docker commented on content/manuals/security/for-admins/hardened-desktop/settings-management/configure-admin-console.md
> +organization for configurations to take effect.
```suggestion
- [Enforce sign-in](/manuals/security/for-admins/enforce-sign-in/_index.md). The Settings Management feature requires a Docker Business subscription, therefore your Docker Desktop users must authenticate to your
organization for configurations to take effect. 
```

2024-11-13 16:18 UTC, sarahsanders-docker commented on content/manuals/security/for-admins/hardened-desktop/settings-management/configure-admin-console.md
> +6. Configure the settings for the policy. Go through each setting and select your chosen setting state. You can choose
```suggestion
6. Configure the settings for the policy. Go through each setting and select your chosen setting state. You can choose:
```

2024-11-13 16:20 UTC, sarahsanders-docker commented on content/manuals/security/for-admins/hardened-desktop/settings-management/configure-admin-console.md
> +If your settings policy needs to be rolled back, either delete the policy or edit the policy to set individual settings to **User-defined**.
```suggestion

If your settings policy needs to be rolled back, either delete the policy or edit the policy to set individual settings to **User-defined**.
```

2024-11-13 16:20 UTC, sarahsanders-docker commented on content/manuals/security/for-admins/hardened-desktop/settings-management/configure-admin-console.md
> +If your settings policy needs to be rolled back, either delete the policy or edit the policy to set individual settings to **User-defined**.
whitespace nit

2024-11-13 16:23 UTC, sarahsanders-docker requested changes
looks good! left a few nits but overall the information is clear and easy to follow :)

2024-11-13 17:28 UTC, dvdksn commented on _vale/config/vocabularies/Docker/accept.txt
> +Docker Admin Console
Not needed; fixed in [#21422](https://github.com/docker/docs/pull/21422)

2024-11-19 15:41 UTC, sarahsanders-docker approved these changes
LGTM! :)

2024-11-21 14:59 UTC, merged